# Generated by Django 3.1.4 on 2020-12-16 13:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Alumno',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('carrera', models.CharField(max_length=23)),
                ('ingreso', models.IntegerField()),
                ('codigo', models.IntegerField()),
                ('apellidos', models.CharField(max_length=21)),
                ('nombre', models.CharField(max_length=22)),
                ('ci', models.IntegerField()),
            ],
            options={
                'db_table': 'alumno',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Institucion',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('codigo_departamento', models.IntegerField()),
                ('nombre_departamento', models.CharField(max_length=19)),
                ('codigo_distrito', models.IntegerField()),
                ('nombre_distrito', models.CharField(max_length=31)),
                ('codigo_barrio_localidad', models.DecimalField(blank=True, decimal_places=1, max_digits=7, null=True)),
                ('nombre_barrio_localidad', models.CharField(blank=True, max_length=43, null=True)),
                ('codigo_zona', models.DecimalField(blank=True, decimal_places=1, max_digits=3, null=True)),
                ('nombre_zona', models.CharField(blank=True, max_length=6, null=True)),
                ('codigo_establecimiento', models.CharField(max_length=7)),
                ('codigo_institucion', models.CharField(max_length=7)),
                ('nombre_institucion', models.CharField(max_length=99)),
                ('sector_o_tipo_gestion', models.CharField(blank=True, max_length=21, null=True)),
                ('niveles_modalidades', models.CharField(max_length=50)),
            ],
            options={
                'db_table': 'institucion',
                'managed': False,
            },
        ),
    ]
